export const TriggerRental = 'TriggerRental'
export const RentalFunctionFinish = 'RentalFunctionFinish'

export const RECEIPT = 'RECEIPT'
export const NORMAL = 'NORMAL'
export const WARNING = 'WARNING'
export const CUTOFF = 'CUTOFF'
export const EXTENSION = 'EXTENSION'
export const ERROR = 'ERROR'
export const LOW_BALANCE = 'LOW_BALANCE'
export const LOW_LIMIT = 'LOW_LIMIT'
export const LOW_HASHRATE = 'LOW_HASHRATE'
export const RENTAL_SUCCESS = 'RENTAL_SUCCESS'
export const RENTAL_WARNING = 'RENTAL_WARNING'
export const RENTAL_ERROR = 'RENTAL_ERROR'

export const ManualRent = 'ManualRent'
export const SpotRent = 'SpotRent'
export const TradeBot = 'TradeBot'
export const SpartanSense = 'SpartanSense'
export const CollectiveDefense = 'CollectiveDefense'

export const error = 'error'
export const StartupSpotRentalStrategy = 'StartupSpotRentalStrategy'
export const StartupChainScanner = 'StartupChainScanner'
export const NODE_SYNCED = 'NODE_SYNCED'
export const CHECK_SPOT_PROFIT = 'CHECK_SPOT_PROFIT'
export const CHECK_NODE_STATUS = 'CHECK_NODE_STATUS'
export const STARTUP = 'STARTUP'
